services:
  application-product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    networks:
      - shopping-network
    ports:
      - 8081:8081
    depends_on:
      - pgadmin-container;

  postgres-container:
    container_name: postgres-container
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - shopping-network
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "products-db"

  pgadmin-container:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "811@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
      - postgres-container
    networks:
      - shopping-network

  prometheus-compose:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - shopping-network

networks:
  shopping-network:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
