server:
  port: 8081

spring:
  application:
    name: product-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  datasource:
    url: jdbc:postgresql://postgres-container:5432/products-db
    password: postgres
    username: postgres
    hikari:
      schema: products
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://postgres-container:5432/products-db
    schemas: products
    user: postgres
    password: postgres

management:

  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring:application:name}
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: true