server:
  port: 8081

spring:
  application:
    name: product-api

  datasource:
    url: jdbc:postgresql://postgres-container:5432/products-db
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring:application:name}
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true